[project]
name = "dianping-bert"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "datasets>=5.0.1",
    "matplotlib>=3.11.1",
    "modelscope>=1.40.0",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.0",
    "tabulate>=0.10.0",
    "torch>=2.14.0",
    "tqdm>=4.70.0",
    "transformers>=5.17.0",
]

[dependency-groups]
dev = [
    "pandas-stubs>=3.0.5.260730",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
ignore = ["E402", "E702", "E731"]
